name: build VAuthenticator Management UI

on:
  push: { }
  workflow_dispatch:
    inputs:
      version:
        description: 'make a tag'
        required: false

      newversion:
        description: 'Next desired version'
        required: true
        type: string
jobs:
#  tag-artifact:
#    if: github.event.inputs.version != '' || github.event.inputs.version != ' '
#    needs:
#      - build-backend
#      - ui-backend
#
#    runs-on: ubuntu-22.04
#    steps:
#      - name: checkout
#        uses: actions/checkout@v4
#
#      - name: make an echo
#        run: |
#          echo version ${{github.event.inputs.version}}
#
#      - name: set the Tag version
#        run: |
#          git config --global user.email "${{ secrets.GIT_EMAIL }}"
#          git config --global user.name "${{ secrets.GIT_USERNAME }}"
#
#          mvn versions:set -DnewVersion=${{github.event.inputs.version}}
#          git commit -am "[skip-ci] new version release ${{github.event.inputs.version}}"
#          git push
#
#      - name: Create tag
#        uses: ncipollo/release-action@v1
#        with:
#          bodyFile: changelog/${{github.event.inputs.version}}.md
#          tag: ${{github.event.inputs.version}}
#
#      - name: set the Next Development version
#        run: |
#          git config --global user.email "${{ secrets.GIT_EMAIL }}"
#          git config --global user.name "${{ secrets.GIT_USERNAME }}"
#
#          mvn versions:set -DnewVersion=${{github.event.inputs.newversion}}
#          git commit -am "[skip-ci] new version release ${{github.event.inputs.newversion}}"
#          git push
  build-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Build
        run: |
          cd management-ui
          ./build.sh
